### ISSUE TITLE
VS2015 -> XAML View not working any more

### ISSUE THREAD

**Issue by jogibear9988** [mono/roslyn#8]
I got the following Exception when trying to use XAML View:

Intellisense could not be initialized due to the following error: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Metadata.ManagedXmlnsDefinitionMap.AddNamespace(IAssembly assembly, IXmlNamespace xmlNamespace, String clrNamespace)
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Platform.Wpf.WpfXmlnsDefinitionMap.RegisterAssemblyNamespaces(IAssembly assembly, IEnumerable`1 attributes)
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Metadata.ManagedXmlnsDefinitionMap.RegisterAssemblies(IEnumerable`1 referencedAssemblies)
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Platform.Wpf.WpfPlatformMetadata.CreateXmlnsDefinitionMap(ManagedTypeResolver typeResolver)
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Metadata.ManagedPlatformMetadata.Reset()
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Metadata.ManagedPlatformMetadata.Initialize(ITypeResolver typeResolver)
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Metadata.ManagedTypeResolverService.GetTypeResolver(IHostProject hostProject)
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.XamlFileInformationService.CreateFileInformationContext(IHostSourceItem sourceItem)
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.XamlLanguageService.EnsureBufferCache(IVsTextLines textLines)
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.XamlLanguageService.CreateSource(IVsTextLines textLines)
Intellisense could not be initialized due to the following error: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Metadata.ManagedXmlnsDefinitionMap.AddNamespace(IAssembly assembly, IXmlNamespace xmlNamespace, String clrNamespace)
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Platform.Wpf.WpfXmlnsDefinitionMap.RegisterAssemblyNamespaces(IAssembly assembly, IEnumerable`1 attributes)
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Metadata.ManagedXmlnsDefinitionMap.RegisterAssemblies(IEnumerable`1 referencedAssemblies)
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Platform.Wpf.WpfPlatformMetadata.CreateXmlnsDefinitionMap(ManagedTypeResolver typeResolver)
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Metadata.ManagedPlatformMetadata.Reset()
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Metadata.ManagedPlatformMetadata.Initialize(ITypeResolver typeResolver)
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Metadata.ManagedTypeResolverService.GetTypeResolver(IHostProject hostProject)
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.XamlFileInformationService.CreateFileInformationContext(IHostSourceItem sourceItem)
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.XamlLanguageService.EnsureBufferCache(IVsTextLines textLines)
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.XamlLanguageService.CreateSource(IVsTextLines textLines)

**Comment by DavidKarlas** [comment]
Not sure what is proper channel for reporting VS2015 bugs but If you want to report to Roslyn team you should use https://github.com/dotnet/roslyn/issues which is offical roslyn GitHub repository. This repository is just for changes needed to compile roslyn source code on *nix.

**Comment by jogibear9988** [comment]
sorry, wrong repo...
